// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: parameter_server.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Parameterserver {
  public static partial class ParameterServer
  {
    static readonly string __ServiceName = "parameterserver.ParameterServer";

    static readonly grpc::Marshaller<global::Parameterserver.GetParamRequest> __Marshaller_parameterserver_GetParamRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Parameterserver.GetParamRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Parameterserver.ParamValue> __Marshaller_parameterserver_ParamValue = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Parameterserver.ParamValue.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Parameterserver.SetParamRequest> __Marshaller_parameterserver_SetParamRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Parameterserver.SetParamRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Std.Empty> __Marshaller_std_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Std.Empty.Parser.ParseFrom);

    static readonly grpc::Method<global::Parameterserver.GetParamRequest, global::Parameterserver.ParamValue> __Method_GetParameter = new grpc::Method<global::Parameterserver.GetParamRequest, global::Parameterserver.ParamValue>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetParameter",
        __Marshaller_parameterserver_GetParamRequest,
        __Marshaller_parameterserver_ParamValue);

    static readonly grpc::Method<global::Parameterserver.SetParamRequest, global::Std.Empty> __Method_SetParameter = new grpc::Method<global::Parameterserver.SetParamRequest, global::Std.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetParameter",
        __Marshaller_parameterserver_SetParamRequest,
        __Marshaller_std_Empty);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Parameterserver.ParameterServerReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ParameterServer</summary>
    public abstract partial class ParameterServerBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Parameterserver.ParamValue> GetParameter(global::Parameterserver.GetParamRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Std.Empty> SetParameter(global::Parameterserver.SetParamRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ParameterServer</summary>
    public partial class ParameterServerClient : grpc::ClientBase<ParameterServerClient>
    {
      /// <summary>Creates a new client for ParameterServer</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ParameterServerClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ParameterServer that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ParameterServerClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ParameterServerClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ParameterServerClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Parameterserver.ParamValue GetParameter(global::Parameterserver.GetParamRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetParameter(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Parameterserver.ParamValue GetParameter(global::Parameterserver.GetParamRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetParameter, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Parameterserver.ParamValue> GetParameterAsync(global::Parameterserver.GetParamRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetParameterAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Parameterserver.ParamValue> GetParameterAsync(global::Parameterserver.GetParamRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetParameter, null, options, request);
      }
      public virtual global::Std.Empty SetParameter(global::Parameterserver.SetParamRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetParameter(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Std.Empty SetParameter(global::Parameterserver.SetParamRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetParameter, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Std.Empty> SetParameterAsync(global::Parameterserver.SetParamRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetParameterAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Std.Empty> SetParameterAsync(global::Parameterserver.SetParamRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetParameter, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ParameterServerClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ParameterServerClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ParameterServerBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetParameter, serviceImpl.GetParameter)
          .AddMethod(__Method_SetParameter, serviceImpl.SetParameter).Build();
    }

  }
}
#endregion
