// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ping.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Ping {
  public static partial class Ping
  {
    static readonly string __ServiceName = "ping.Ping";

    static readonly grpc::Marshaller<global::Ping.PingMsg> __Marshaller_ping_PingMsg = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Ping.PingMsg.Parser.ParseFrom);

    static readonly grpc::Method<global::Ping.PingMsg, global::Ping.PingMsg> __Method_Ping = new grpc::Method<global::Ping.PingMsg, global::Ping.PingMsg>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Ping",
        __Marshaller_ping_PingMsg,
        __Marshaller_ping_PingMsg);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Ping.PingReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Ping</summary>
    public abstract partial class PingBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Ping.PingMsg> Ping(global::Ping.PingMsg request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Ping</summary>
    public partial class PingClient : grpc::ClientBase<PingClient>
    {
      /// <summary>Creates a new client for Ping</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PingClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Ping that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PingClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PingClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PingClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Ping.PingMsg Ping(global::Ping.PingMsg request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Ping(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Ping.PingMsg Ping(global::Ping.PingMsg request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Ping, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Ping.PingMsg> PingAsync(global::Ping.PingMsg request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PingAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Ping.PingMsg> PingAsync(global::Ping.PingMsg request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Ping, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PingClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PingClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(PingBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Ping, serviceImpl.Ping).Build();
    }

  }
}
#endregion
