// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: remote_control.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Remotecontrol {
  public static partial class RemoteControl
  {
    static readonly string __ServiceName = "remotecontrol.RemoteControl";

    static readonly grpc::Marshaller<global::Remotecontrol.ForceRequest> __Marshaller_remotecontrol_ForceRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Remotecontrol.ForceRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Remotecontrol.ForceResponse> __Marshaller_remotecontrol_ForceResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Remotecontrol.ForceResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Remotecontrol.ForceRequest, global::Remotecontrol.ForceResponse> __Method_ApplyForce = new grpc::Method<global::Remotecontrol.ForceRequest, global::Remotecontrol.ForceResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "ApplyForce",
        __Marshaller_remotecontrol_ForceRequest,
        __Marshaller_remotecontrol_ForceResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Remotecontrol.RemoteControlReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of RemoteControl</summary>
    public abstract partial class RemoteControlBase
    {
      public virtual global::System.Threading.Tasks.Task ApplyForce(global::Remotecontrol.ForceRequest request, grpc::IServerStreamWriter<global::Remotecontrol.ForceResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for RemoteControl</summary>
    public partial class RemoteControlClient : grpc::ClientBase<RemoteControlClient>
    {
      /// <summary>Creates a new client for RemoteControl</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public RemoteControlClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for RemoteControl that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public RemoteControlClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected RemoteControlClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected RemoteControlClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::Remotecontrol.ForceResponse> ApplyForce(global::Remotecontrol.ForceRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ApplyForce(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Remotecontrol.ForceResponse> ApplyForce(global::Remotecontrol.ForceRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_ApplyForce, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override RemoteControlClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new RemoteControlClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(RemoteControlBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_ApplyForce, serviceImpl.ApplyForce).Build();
    }

  }
}
#endregion
