// Generated by gencpp from file uwr_comms/comms1.msg
// DO NOT EDIT!


#ifndef UWR_COMMS_MESSAGE_COMMS1_H
#define UWR_COMMS_MESSAGE_COMMS1_H

#include <ros/service_traits.h>


#include <uwr_comms/comms1Request.h>
#include <uwr_comms/comms1Response.h>


namespace uwr_comms
{

struct comms1
{

typedef comms1Request Request;
typedef comms1Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct comms1
} // namespace uwr_comms


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uwr_comms::comms1 > {
  static const char* value()
  {
    return "0242c4536209073ea8ef950661c5aa97";
  }

  static const char* value(const ::uwr_comms::comms1&) { return value(); }
};

template<>
struct DataType< ::uwr_comms::comms1 > {
  static const char* value()
  {
    return "uwr_comms/comms1";
  }

  static const char* value(const ::uwr_comms::comms1&) { return value(); }
};


// service_traits::MD5Sum< ::uwr_comms::comms1Request> should match
// service_traits::MD5Sum< ::uwr_comms::comms1 >
template<>
struct MD5Sum< ::uwr_comms::comms1Request>
{
  static const char* value()
  {
    return MD5Sum< ::uwr_comms::comms1 >::value();
  }
  static const char* value(const ::uwr_comms::comms1Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::uwr_comms::comms1Request> should match
// service_traits::DataType< ::uwr_comms::comms1 >
template<>
struct DataType< ::uwr_comms::comms1Request>
{
  static const char* value()
  {
    return DataType< ::uwr_comms::comms1 >::value();
  }
  static const char* value(const ::uwr_comms::comms1Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uwr_comms::comms1Response> should match
// service_traits::MD5Sum< ::uwr_comms::comms1 >
template<>
struct MD5Sum< ::uwr_comms::comms1Response>
{
  static const char* value()
  {
    return MD5Sum< ::uwr_comms::comms1 >::value();
  }
  static const char* value(const ::uwr_comms::comms1Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::uwr_comms::comms1Response> should match
// service_traits::DataType< ::uwr_comms::comms1 >
template<>
struct DataType< ::uwr_comms::comms1Response>
{
  static const char* value()
  {
    return DataType< ::uwr_comms::comms1 >::value();
  }
  static const char* value(const ::uwr_comms::comms1Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UWR_COMMS_MESSAGE_COMMS1_H
