// Generated by gencpp from file uwr_comms/comms1Request.msg
// DO NOT EDIT!


#ifndef UWR_COMMS_MESSAGE_COMMS1REQUEST_H
#define UWR_COMMS_MESSAGE_COMMS1REQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uwr_comms
{
template <class ContainerAllocator>
struct comms1Request_
{
  typedef comms1Request_<ContainerAllocator> Type;

  comms1Request_()
    : data()  {
    }
  comms1Request_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::uwr_comms::comms1Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uwr_comms::comms1Request_<ContainerAllocator> const> ConstPtr;

}; // struct comms1Request_

typedef ::uwr_comms::comms1Request_<std::allocator<void> > comms1Request;

typedef boost::shared_ptr< ::uwr_comms::comms1Request > comms1RequestPtr;
typedef boost::shared_ptr< ::uwr_comms::comms1Request const> comms1RequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uwr_comms::comms1Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uwr_comms::comms1Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uwr_comms::comms1Request_<ContainerAllocator1> & lhs, const ::uwr_comms::comms1Request_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uwr_comms::comms1Request_<ContainerAllocator1> & lhs, const ::uwr_comms::comms1Request_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uwr_comms

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uwr_comms::comms1Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uwr_comms::comms1Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uwr_comms::comms1Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uwr_comms::comms1Request_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uwr_comms::comms1Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uwr_comms::comms1Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uwr_comms::comms1Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "420cd38b6b071cd49f2970c3e2cee511";
  }

  static const char* value(const ::uwr_comms::comms1Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x420cd38b6b071cd4ULL;
  static const uint64_t static_value2 = 0x9f2970c3e2cee511ULL;
};

template<class ContainerAllocator>
struct DataType< ::uwr_comms::comms1Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uwr_comms/comms1Request";
  }

  static const char* value(const ::uwr_comms::comms1Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uwr_comms::comms1Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] data\n"
;
  }

  static const char* value(const ::uwr_comms::comms1Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uwr_comms::comms1Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct comms1Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uwr_comms::comms1Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uwr_comms::comms1Request_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UWR_COMMS_MESSAGE_COMMS1REQUEST_H
