// Generated by gencpp from file uwr_comms/comms1Response.msg
// DO NOT EDIT!


#ifndef UWR_COMMS_MESSAGE_COMMS1RESPONSE_H
#define UWR_COMMS_MESSAGE_COMMS1RESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uwr_comms
{
template <class ContainerAllocator>
struct comms1Response_
{
  typedef comms1Response_<ContainerAllocator> Type;

  comms1Response_()
    : response()
    , data()  {
    }
  comms1Response_(const ContainerAllocator& _alloc)
    : response(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _response_type;
  _response_type response;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::uwr_comms::comms1Response_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uwr_comms::comms1Response_<ContainerAllocator> const> ConstPtr;

}; // struct comms1Response_

typedef ::uwr_comms::comms1Response_<std::allocator<void> > comms1Response;

typedef boost::shared_ptr< ::uwr_comms::comms1Response > comms1ResponsePtr;
typedef boost::shared_ptr< ::uwr_comms::comms1Response const> comms1ResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uwr_comms::comms1Response_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uwr_comms::comms1Response_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uwr_comms::comms1Response_<ContainerAllocator1> & lhs, const ::uwr_comms::comms1Response_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uwr_comms::comms1Response_<ContainerAllocator1> & lhs, const ::uwr_comms::comms1Response_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uwr_comms

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uwr_comms::comms1Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uwr_comms::comms1Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uwr_comms::comms1Response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uwr_comms::comms1Response_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uwr_comms::comms1Response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uwr_comms::comms1Response_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uwr_comms::comms1Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "337d6db012d6223057ef6437080f6409";
  }

  static const char* value(const ::uwr_comms::comms1Response_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x337d6db012d62230ULL;
  static const uint64_t static_value2 = 0x57ef6437080f6409ULL;
};

template<class ContainerAllocator>
struct DataType< ::uwr_comms::comms1Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uwr_comms/comms1Response";
  }

  static const char* value(const ::uwr_comms::comms1Response_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uwr_comms::comms1Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string response\n"
"float32[] data\n"
"\n"
;
  }

  static const char* value(const ::uwr_comms::comms1Response_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uwr_comms::comms1Response_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct comms1Response_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uwr_comms::comms1Response_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uwr_comms::comms1Response_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.response);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UWR_COMMS_MESSAGE_COMMS1RESPONSE_H
